branches:
  only:
    - master

language: node_js
node_js:
  - node
script: echo "Running tests against $(node -v)..."

before_install:
- npm update

install:
- npm install
- npm run build

git:
  depth: false
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      if: branch = master AND type = pull_request
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: Deploy on NPM
      if: branch = master AND type = push
      before_deploy:  
      - npm run postBuild
      - git checkout
      - git add .
      - git commit "new version"
      - npm version patch
      deploy:
        # Deploy Surge
        - provider: surge
          skip_cleanup: true
          domain: react-prebid-rubicon.surge.sh  
          on:
            branch: master
        # Deploy NPM
        - provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
          on:
            branch: master
            repo: AntoineJac/react-prebid-rubicon
